### ISSUE TITLE
thinking in react branch: loggedUser is defined but never used

### ISSUE THREAD

**Issue by jsms90** [reactjsacademy/fb-messenger#8]
`loggedUser` is defined as a variable [on this line in `App.js`](https://github.com/leanjscom/fb-messenger/blob/thinking-in-react/src/App.js#L64) but this variable is not used anywhere

I'm guessing the intent was to use it [on this line, where Alex is hardcoded](https://github.com/leanjscom/fb-messenger/blob/thinking-in-react/src/App.js#L76)?

Perhaps it's worth either removing the line that creates the `loggedUser` variable, or using it in the link: 
```
<a
  onClick={this.toggleModal}
  className={`username ${this.userPosition || "left"}`}
>
  {loggedUser}
</a>
```

Just to save potential confusion during the refactor stages.

**Comment by flexbox** [comment]
Fixed with https://github.com/leanjscom/fb-messenger/pull/4 ?
